name: Run Selenium IDE Tests Daily

on:
  workflow_dispatch:  # 👈 This enables manual trigger
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 9:00 AM IST (3:30 AM UTC)

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Selenium IDE Runner
        run: |
          npm install -g selenium-side-runner
          npm install -g chromedriver

      - name: Run Selenium IDE Tests
        run: |
          selenium-side-runner \
            --browser chrome \
            --capabilities chromeOptions.args="['--headless','--no-sandbox','--disable-dev-shm-usage','--user-data-dir=/tmp/profile']" \
            FastResumeUpdate.side
