name: Run Selenium IDE Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'  # 9 AM IST

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Selenium-side-runner
        run: |
          npm install -g selenium-side-runner
          npm install -g chromedriver

      - name: Run Selenium IDE Tests
        run: |
          mkdir -p /tmp/profile-$RANDOM
          selenium-side-runner \
            --browser chrome \
            --capabilities "goog:chromeOptions={args:['--headless','--no-sandbox','--disable-dev-shm-usage','--user-data-dir=/tmp/profile-$RANDOM']}" \
            FastResumeUpdate.side
